CREATE TABLE IF NOT EXISTS catalogo (
  id SERIAL PRIMARY KEY,
  nombre TEXT UNIQUE NOT NULL,
  precio NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS registros (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL,
  cantidad INTEGER NOT NULL,
  precio NUMERIC NOT NULL,
  fecha TIMESTAMP NOT NULL,
  total NUMERIC NOT NULL
);
